[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
backend = "5jL8NFLSUhPrkto2RuNANXehBDrRNsYTD6acAxKNCZKp"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
